version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "8088:80"
    volumes:
    - ./symfplay:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql


  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
    - ./symfplay:/var/www/html
    ports:
    - "9000:9000"

  composer:
    image: composer:latest
    container_name: composer
    volumes:
    - ./symfplay:/var/www/html
    working_dir: /var/www/html

  npm:
    image: node:15.3.0-alpine3.10
    container_name: npm
    volumes:
    - ./symfplay:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']


